[package]
name = "playable_bosses"
version = "1.0.0"
authors = ["GamerSubzero <putsomeemailhere@someemailaddress>, Nemesis69 <pepeisnoice@gmail.com>, jam1garner <jam1.mcleod@hotmail.com>"]
edition = "2018"

[package.metadata.skyline]
titleid = "01006A800016E000"

[lib]
crate-type = ["cdylib"]

[dependencies]
skyline = { git = "https://github.com/ultimate-research/skyline-rs.git" }
skyline_smash = { git = "https://github.com/ultimate-research/skyline-smash.git" }
acmd = { git = "https://github.com/ultimate-research/skyline-acmd.git" }
serde = { version = "1.0", features = ["derive"] }
parking_lot = "0.11.0"
toml = "0.5.6"
lazy_static = "1.4"
smash_script = { git = "https://github.com/blu-dev/smash-script.git" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true